
INSERT INTO MPA(mpa_id, mpa)
SELECT * FROM (SELECT 1, 'G') AS tmp
WHERE NOT EXISTS(
        SELECT MPA_id FROM MPA WHERE MPA_id = 1
    ) LIMIT 1;

INSERT INTO MPA(mpa_id, mpa)
SELECT * FROM (SELECT 2, 'PG') AS tmp
WHERE NOT EXISTS(
        SELECT MPA_id FROM MPA WHERE MPA_id = 2
    ) LIMIT 1;

INSERT INTO MPA(mpa_id, mpa)
SELECT * FROM (SELECT 3, 'PG-13') AS tmp
WHERE NOT EXISTS(
        SELECT MPA_id FROM MPA WHERE MPA_id = 3
    ) LIMIT 1;

INSERT INTO MPA(mpa_id, mpa)
SELECT * FROM (SELECT 4, 'R') AS tmp
WHERE NOT EXISTS(
        SELECT MPA_id FROM MPA WHERE MPA_id = 4
    ) LIMIT 1;

INSERT INTO MPA(mpa_id, mpa)
SELECT * FROM (SELECT 5, 'NC-17') AS tmp
WHERE NOT EXISTS(
        SELECT MPA_id FROM MPA WHERE MPA_id = 5
    ) LIMIT 1;




INSERT INTO GENRES(ID,GENRE)
SELECT * FROM (SELECT 1,'Комедия') AS tmp
WHERE NOT EXISTS(
        SELECT ID FROM GENRES WHERE ID = 1
    ) LIMIT 1;

INSERT INTO GENRES(ID,GENRE)
SELECT * FROM (SELECT 2,'Драма') AS tmp
WHERE NOT EXISTS(
        SELECT ID FROM GENRES WHERE ID = 2
    ) LIMIT 1;

INSERT INTO GENRES(ID,GENRE)
SELECT * FROM (SELECT 3,'Мультфильм') AS tmp
WHERE NOT EXISTS(
        SELECT ID FROM GENRES WHERE ID = 3
    ) LIMIT 1;

INSERT INTO GENRES(ID,GENRE)
SELECT * FROM (SELECT 4,'Триллер') AS tmp
WHERE NOT EXISTS(
        SELECT ID FROM GENRES WHERE ID = 4
    ) LIMIT 1;

INSERT INTO GENRES(ID,GENRE)
SELECT * FROM (SELECT 5,'Документальный') AS tmp
WHERE NOT EXISTS(
        SELECT ID FROM GENRES WHERE ID = 5
    ) LIMIT 1;

INSERT INTO GENRES(ID,GENRE)
SELECT * FROM (SELECT 6,'Боевик') AS tmp
WHERE NOT EXISTS(
        SELECT ID FROM GENRES WHERE ID = 6
    ) LIMIT 1;

INSERT INTO GENRES(ID,GENRE)
SELECT * FROM (SELECT 6,'Crime') AS tmp
WHERE NOT EXISTS(
        SELECT ID FROM GENRES WHERE ID = 6
    ) LIMIT 1;

DELETE FROM films;
DELETE FROM USERS;
DELETE FROM FILM_GENRES;
DELETE FROM FILM_LIKERS;
DELETE FROM USER_FRIENDS;
DELETE FROM films;

